package exception;

/*
 * 예외처리
 * 
 */
public class ExceptionEx1 {

	public static void main(String[] args) {
		/* 오랜만에 argument 처리
		 * $ java ExceptionEx1 2 ==> 2
		 * $ java ExceptionEx1 0 ==> error
		 * 
		 */
		int var=5;
		try {
		int n=Integer.parseInt(args[0]);
		System.out.println(var/n);
		}catch(ArithmeticException e) {//객체를 잡겠다 
			System.out.println("0으로 나눌수 없어요");
		}

}
